name: CI/CD for CarPricePredictor

on:
  push:
    branches:
      - main # trigger on push to main branch
  pull_request:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pandas numpy scikit-learn mlflow joblib

      - name: Run model tests
        run: |
          python test.py

  deploy:
    name: Deploy if Tests Pass
    needs: test
    runs-on: ubuntu-latest
    if: success()
    env:
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_PASSWORD }}
      MLFLOW_URL: ${{ secrets.MLFLOW_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow

      - name: Deploy Model to MLflow
        env:
          MLFLOW_TRACKING_URI: https://mlflow.ml.brain.cs.ait.ac.th/
        run: |
          python deploy_model.py

      - name: Deployment success
        run: |
          echo "Model deployed successfully to MLflow!"